id: ADBA4DDA4
base_file: f170E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:03:47.062803
  last_modified_at: 2022-06-17 11:03:47.062807
