id: ADBA4DDA4
base_file: f09EA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:03:47.060477
  last_modified_at: 2022-06-17 11:03:47.060484
