id: ADBA4DDA4
base_file: f73A1.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:03:47.066952
  last_modified_at: 2022-06-17 11:03:47.066955
