id: ADBA4DDA4
base_file: fC2C1.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:03:47.071378
  last_modified_at: 2022-06-17 11:03:47.071385
